# Data Types and Type Conversion
Task 20 - Day 20

In [1]:
import pandas as pd

# every column loaded as plain text, as if read from a messy CSV
df = pd.DataFrame({
    "Name": ["Asha", "Raj", "Meena", "Vikram", "Priya"],
    "Age": ["23", "25", "22", "24", "26"],
    "Salary": ["45000", "62000", "38000", "71000", "50000"],
    "Joined": ["2023-01-15", "2022-06-10", "2024-03-01", "2021-11-20", "2023-08-05"],
    "IsActive": ["True", "False", "True", "True", "False"],
    "Rating": ["4.5", "3.8", "4.9", "4.1", "3.5"],
})
df

     Name Age Salary      Joined IsActive Rating
0    Asha  23  45000  2023-01-15     True    4.5
1     Raj  25  62000  2022-06-10    False    3.8
2   Meena  22  38000  2024-03-01     True    4.9
3  Vikram  24  71000  2021-11-20     True    4.1
4   Priya  26  50000  2023-08-05    False    3.5

## Data-type inspection report

In [2]:
print(df.dtypes)

Name        str
Age         str
Salary      str
Joined      str
IsActive    str
Rating      str
dtype: object

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      str
 1   Age       5 non-null      str
 2   Salary    5 non-null      str
 3   Joined    5 non-null      str
 4   IsActive  5 non-null      str
 5   Rating    5 non-null      str
dtypes: str(6)
memory usage: 372.0 bytes

## Converting column types

In [4]:
# 1. string to integer
df["Age"] = df["Age"].astype(int)
print(df["Age"].dtype)

int64

In [5]:
# 2. string to float
df["Rating"] = df["Rating"].astype(float)
print(df["Rating"].dtype)

float64

In [6]:
# 3. string to integer using pd.to_numeric()
df["Salary"] = pd.to_numeric(df["Salary"])
print(df["Salary"].dtype)

int64

In [7]:
# 4. string to boolean
df["IsActive"] = df["IsActive"].map({"True": True, "False": False})
print(df["IsActive"].dtype)

bool

In [8]:
# 5. string to datetime
df["Joined"] = pd.to_datetime(df["Joined"])
print(df["Joined"].dtype)

datetime64[us]

In [9]:
# 6. integer back to string
df["AgeStr"] = df["Age"].astype(str)
print(df["AgeStr"].dtype)

str

## The cleaned dataset

In [10]:
print(df.dtypes)

Name                   str
Age                  int64
Salary               int64
Joined      datetime64[us]
IsActive              bool
Rating             float64
AgeStr                 str
dtype: object

In [11]:
df

     Name  Age  Salary     Joined  IsActive  Rating AgeStr
0    Asha   23   45000 2023-01-15      True     4.5     23
1     Raj   25   62000 2022-06-10     False     3.8     25
2   Meena   22   38000 2024-03-01      True     4.9     22
3  Vikram   24   71000 2021-11-20      True     4.1     24
4   Priya   26   50000 2023-08-05     False     3.5     26

## Handling conversion errors

In [12]:
# a column with one invalid value mixed in
messy = pd.Series(["10", "20", "abc", "40"])

# astype() would raise an error here, so pd.to_numeric with errors="coerce"
# turns the bad value into NaN instead of crashing
cleaned = pd.to_numeric(messy, errors="coerce")
print(cleaned)

0    10.0
1    20.0
2     NaN
3    40.0
dtype: float64

## Interview questions

**Why are correct data types important?**
Wrong types quietly break analysis. A numeric column left as text can't be summed, averaged, or compared numerically — `"45000" > "7000"` actually evaluates as a string comparison and gives the wrong answer. Dates stored as text can't be sorted chronologically or have day/month/year extracted. Correct types also reduce memory usage significantly compared to storing everything as text.

**What does astype() do?**
It converts a Series or an entire DataFrame to a specified data type, such as `.astype(int)`, `.astype(float)`, `.astype(str)`, or `.astype("datetime64[ns]")`. It raises an error immediately if any value in the column can't be converted, which makes it strict but also useful for catching bad data early.

**How can you convert a string column to numeric?**
With `.astype(int)` or `.astype(float)` when every value is guaranteed valid, or with `pd.to_numeric()` when the column might contain some invalid entries — passing `errors="coerce"` turns anything that can't be converted into `NaN` instead of crashing the whole operation, which is safer for real-world messy data.